Diplomska/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diplomska.Models;
using Diplomska.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Diplomska.ViewModels;
using System.Security.Claims;
using Diplomska.Data;

namespace Diplomska.Controllers
{
    public class EventsController : Controller
    {
        private readonly DiplomskaContext _context;
        private readonly UserManager<DiplomskaUser> _userManager;
        private readonly SignInManager<DiplomskaUser> _signInManager;


        public EventsController(DiplomskaContext context, UserManager<DiplomskaUser> UserManager, SignInManager<DiplomskaUser> SignInManager)
        {
            _userManager = UserManager;
            _signInManager = SignInManager;
            _context = context;
        }


        static string authSecret = "Vf2xi4idcUd9yD7YfnrCiAokIY3oe2pUdjYRpVN3";
        static string basePath = "https://diplomska-11f45-default-rtdb.europe-west1.firebasedatabase.app/";

        IFirebaseClient client;

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = authSecret,
            BasePath = basePath
        };

        // GET: Events
        public async Task<IActionResult> Index()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("events");
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Event>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Event>(((JProperty)item).Value.ToString()));
            }
            IQueryable<Event> movies = list.AsQueryable();
            DateTime currentDateTime = DateTime.Now;
            var enum2 = from user in movies
                        orderby user.Date
                        select user;
            var e = new List<Event>();
            var movieGenreVM = new EventSearch
            {
                Events = enum2.ToList(),
            };
            return View(movieGenreVM);
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(string? id, Edit_EventPicture @event)
        {
            if (id == null)
            {
                return NotFound();
            }
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("events/" + id);
            Event data = JsonConvert.DeserializeObject<Event>(response.Body);
            @event.Event = data;
            @event.Desc = data.Poster;
            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("events");
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Event>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Event>(((JProperty)item).Value.ToString()));
            }
            ViewData["HostName"] = new SelectList(list, "HostName", "Username");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Edit_EventPicture @event)
        {
            string uniqueFileName = null;
            var hoster = User.FindFirstValue(ClaimTypes.Name);
            if (@event.ProfileImage != null)
            {
                uniqueFileName = UploadedFile(@event);
            }
            else
            {
                @event.Desc = uniqueFileName;
            }
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response1 = client.Get("guests/");
            dynamic data1 = JsonConvert.DeserializeObject<dynamic>(response1.Body);
            var list1 = new List<Guest>();
            foreach (var item in data1)
            {
                list1.Add(JsonConvert.DeserializeObject<Guest>(((JProperty)item).Value.ToString()));
            }
            Guest k = list1.Where(m => m.Username == hoster).First();
            Event newEmployee = new Event
            {
                Title = @event.Title,
                Date = @event.Date,
                Time = @event.Time,
                Genre = @event.Genre,
                Price = @event.Price,
                Location = @event.Location,
                Hoster = k,
                HostName = hoster,
                Poster = uniqueFileName
            };
            try
            {
                AddToFirebase(newEmployee);
                AddInterestToFirebase(newEmployee);
                ModelState.AddModelError(string.Empty, "ADded");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }


            return RedirectToAction("Details", new { id = newEmployee.Id });
            return View(@event);
        }

        private void AddInterestToFirebase(Event newEmployee)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = new EventGuest
            {
                Event = newEmployee,
                EventId = newEmployee.Id,
                Guest = newEmployee.Hoster,
                GuestId = newEmployee.Hoster.Username,
            Interest=1
        };
            PushResponse response = client.Push("eventguests/", data);
        }

        private void AddToFirebase(Event @event)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = @event;
            PushResponse response = client.Push("events/", data);
            data.Id = response.Result.name;
            SetResponse setResponse = client.Set("events/" + data.Id, data);

        }
        private string UploadedFile(Edit_EventPicture viewmodel)
        {
            string uniqueFileName = null;

            if (viewmodel.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(viewmodel.ProfileImage.FileName);
                string fileNameWithPath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    viewmodel.ProfileImage.CopyTo(stream);
                }
            }
            return uniqueFileName;
        }
        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("events/" + id);
            Event data = JsonConvert.DeserializeObject<Event>(response.Body);
            Edit_EventPicture viewmodel = new Edit_EventPicture
            {
                Event = data,
                Desc = data.Poster
            };
            return View(viewmodel);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Edit_EventPicture viewmodel)
        {
            string uniqueFileName = null;
            if (id != viewmodel.Event.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.ProfileImage != null)
                    {
                        uniqueFileName = UploadedFile(viewmodel);
                        viewmodel.Event.Poster = uniqueFileName;
                    }
                    else
                    {
                        viewmodel.Event.Poster = viewmodel.Desc;
                    }
                    client = new FireSharp.FirebaseClient(config);
                    SetResponse response = client.Set("events/" + viewmodel.Event.Id, viewmodel.Event);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(viewmodel.Event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = viewmodel.Event.Id });

            }
            return View(viewmodel);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("events/" + id);
            Event data = JsonConvert.DeserializeObject<Event>(response.Body);

            if (data == null)
            {
                return NotFound();
            }
            return View(data);
            return RedirectToAction("Index");
        }

Diplomska/Controllers/GuestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diplomska.Models;
using Diplomska.Data;

namespace Diplomska.Controllers
{
    public class GuestsController : Controller
    {
        private readonly DiplomskaContext _context;

        public GuestsController(DiplomskaContext context)
        {
            _context = context;
        }

        // GET: Guests
        public async Task<IActionResult> Index()
        {
              return _context.Guest != null ? 
                          View(await _context.Guest.ToListAsync()) :
                          Problem("Entity set 'DiplomskaContext.Guest'  is null.");
        }

        // GET: Guests/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Guest == null)
            {
                return NotFound();
            }

            var guest = await _context.Guest
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        // GET: Guests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,user")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(guest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(guest);
        }

        // GET: Guests/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Guest == null)
            {
                return NotFound();
            }

            var guest = await _context.Guest.FindAsync(id);
            if (guest == null)
            {
                return NotFound();
            }
            return View(guest);
        }

        // POST: Guests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Username,user")] Guest guest)
        {
            if (id != guest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuestExists(guest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(guest);
        }

        // GET: Guests/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Guest == null)
            {
                return NotFound();
            }

            var guest = await _context.Guest
                .FirstOrDefaultAsync(m => m.Id == id);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        // POST: Guests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Guest == null)
            {
                return Problem("Entity set 'DiplomskaContext.Guest'  is null.");
            }
            var guest = await _context.Guest.FindAsync(id);
            if (guest != null)
            {
                _context.Guest.Remove(guest);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuestExists(string id)
        {
          return (_context.Guest?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Diplomska/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Diplomska.Areas.Identity.Data
@inject UserManager<DiplomskaUser> UserManager
@inject SignInManager<DiplomskaUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diplomska</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.slim.js"></script>
    <script src="~/lib/jquery/jquery.slim.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Diplomska.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-secondary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Event Planner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>

                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Guests" asp-action="Index">Guests</a>
                            }

                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="EventsHosting" asp-route-ID=@UserManager.GetUserName(User)>Events Hosting</a>
                                }
                            
                        </li>
                        <li class="nav-item">

                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="EventsJoined" asp-route-userID=@UserManager.GetUserName(User)>Events Attending</a>
                            }

                        </li>

                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-light" id="register" asp-area="" asp-controller="Home" asp-action="AllUsers">Users</a>
                            }
                        </li>
                    </ul>

                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-secondary">
        <div class="container">
            &copy; 2023 - Diplomska
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>